services:
  patient-db:
    image: 'mysql:8.0'
    container_name: patient-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mediscreen_patient_db
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - patient-db-data:/var/lib/mysql

  notes-db:
    image: mongo:latest
    container_name: notes-db
    ports:
      - "27017:27017"
    volumes:
      - notes-db-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  patient-db-data:
  notes-db-data: